import { z } from "zod";
import type { PageSection, ProductAsset } from "@prisma/client";

import {
  buildImageEditPrompt,
  buildRegenerationPrompt,
  buildSectionImagePrompt,
  buildSectionSvgLayoutPrompt,
} from "@/lib/ai/prompts";
import { prisma } from "@/lib/db/prisma";
import { getProviderAdapter } from "@/lib/services/provider-service";
import { completeTask, createTask, failTask, findRecentRunningTask } from "@/lib/services/task-service";
import { buildVisualPromptWithAgent } from "@/lib/services/visual-prompt-agent";
import { readStorageFile, saveGeneratedImage } from "@/lib/storage/asset-manager";
import { normalizeContentLanguage, type ContentLanguage } from "@/lib/utils/content-language";
import { buildDefaultVisualStyleGuide, readVisualStyleGuide } from "@/lib/utils/visual-style-guide";
import { sectionTypeLabels } from "@/types/domain";

const svgLayoutSchema = z.object({
  headline: z.string().min(1),
  subheadline: z.string().min(1),
  badge: z.string().min(1),
  highlights: z.array(z.string().min(1)).min(2).max(4),
  backgroundColor: z.string().min(4),
  accentColor: z.string().min(4),
  panelColor: z.string().min(4),
});

const svgCopyByLanguage: Partial<Record<
  ContentLanguage,
  {
    highlights: string;
    waitingForAsset: string;
    footer: string;
  }
>> = {
  "zh-CN": {
    highlights: "核心亮点",
    waitingForAsset: "等待商品图片素材",
    footer: "商品详情模块 · MxPage AI 自动生成",
  },
  "en-US": {
    highlights: "Key Highlights",
    waitingForAsset: "Waiting for product image",
    footer: "Product Detail Section · Auto-generated by MxPage AI",
  },
  "ja-JP": {
    highlights: "主なポイント",
    waitingForAsset: "商品画像を待っています",
    footer: "商品詳細セクション · MxPage AI 自動生成",
  },
  "ko-KR": {
    highlights: "핵심 포인트",
    waitingForAsset: "상품 이미지를 기다리는 중",
    footer: "상품 상세 섹션 · MxPage AI 자동 생성",
  },
};

type ProviderContext = Awaited<ReturnType<typeof getProviderAdapter>>["provider"];
type AdapterContext = Awaited<ReturnType<typeof getProviderAdapter>>["adapter"];
type AssetRecord = Pick<ProductAsset, "id" | "filePath" | "fileName" | "mimeType" | "type" | "isMain">;
type SectionImageAspectRatio = "1:1" | "3:4" | "9:16";

function getGenerationSettings(project: { modelSnapshot: unknown } | null) {
  const snapshot = (project?.modelSnapshot as Record<string, unknown> | null) ?? {};
  const settings = (snapshot.generationSettings as Record<string, unknown> | null) ?? {};
  const previewConfig = (snapshot.previewConfig as Record<string, unknown> | null) ?? {};

  return {
    allowSvgFallback: settings.allowSvgFallback === true,
    imageAspectRatio: previewConfig.imageAspectRatio === "3:4" ? "3:4" : "9:16",
    contentLanguage: normalizeContentLanguage(previewConfig.contentLanguage),
  } as {
    allowSvgFallback: boolean;
    imageAspectRatio: "3:4" | "9:16";
    contentLanguage: ContentLanguage;
  };
}

function getProjectVisualStyleGuide(project: { modelSnapshot: unknown; style?: string | null; platform?: string | null; analysis?: { normalizedResult: unknown } | null }) {
  const analysis = (project.analysis?.normalizedResult as Record<string, unknown> | null) ?? {};
  const fallback = buildDefaultVisualStyleGuide({
    productName: typeof analysis.productName === "string" ? analysis.productName : undefined,
    styleLabel: project.style ?? undefined,
    platformLabel: project.platform ?? undefined,
  });
  return readVisualStyleGuide(project.modelSnapshot, fallback) ?? fallback;
}

function readGenerationRequirements(analysis: unknown) {
  const value = (analysis as Record<string, unknown> | null)?.generationRequirements;
  return typeof value === "string" ? value : "";
}

function getSectionAspectRatio(
  section: Pick<PageSection, "type">,
  detailAspectRatio: "3:4" | "9:16",
): SectionImageAspectRatio {
  return section.type === "HERO" ? "1:1" : detailAspectRatio;
}

function getOutputSize(aspectRatio: SectionImageAspectRatio) {
  if (aspectRatio === "1:1") {
    return "1024x1024";
  }

  return "1024x1536";
}

function isStableImageModel(modelId: string) {
  return !/(preview|experimental|beta|test)/i.test(modelId);
}

function isPreferredImageModel(modelId: string) {
  return /(banana|nano-banana|nano banana|imagen|recraft|flux|gemini|gpt[-_\s]?image|chatgpt-image|dall[-_\s]?e|seedream|jimeng|midjourney|ideogram|hidream|kolors|wanx|cogview)/i.test(modelId);
}

function isGeminiImageModel(modelId: string) {
  return /gemini.*image|nano-banana|banana/i.test(modelId);
}

function isOpenAiGptImageModel(modelId: string) {
  return /(?:^|[-_\s])gpt[-_\s]?image(?:[-_\s]?(?:\d+(?:\.\d+)?|mini))?|chatgpt-image/i.test(modelId);
}

function readCapabilities(model: { capabilities: unknown }) {
  return (model.capabilities as Record<string, boolean> | null) ?? {};
}

function hasImageCapability(model: { capabilities: unknown }) {
  return Boolean(readCapabilities(model).image_gen);
}

function hasTextCapability(model: { capabilities: unknown }) {
  return Boolean(readCapabilities(model).text);
}

function hasVisionCapability(model: { capabilities: unknown }) {
  return Boolean(readCapabilities(model).vision);
}

function hasRealImageGeneration(model: { capabilities: unknown }) {
  return readCapabilities(model).real_image_gen !== false;
}

function hasRealImageEdit(model: { capabilities: unknown }) {
  return readCapabilities(model).real_image_edit !== false;
}

function canGenerateRealImage(model: { capabilities: unknown }) {
  const modelId = (model as { modelId?: string }).modelId ?? "";
  return hasImageCapability(model) && (hasRealImageGeneration(model) || isGeminiImageModel(modelId) || isOpenAiGptImageModel(modelId));
}

function canEditRealImage(model: { capabilities: unknown }) {
  const capabilities = readCapabilities(model);
  const modelId = (model as { modelId?: string }).modelId ?? "";
  return (
    (Boolean(capabilities.image_edit) && capabilities.real_image_edit !== false) ||
    (Boolean(capabilities.image_gen) &&
      (capabilities.real_image_gen !== false || isGeminiImageModel(modelId) || isOpenAiGptImageModel(modelId)))
  );
}

function buildImageModelCandidates(
  provider: ProviderContext,
  options?: {
    preferredModelId?: string | null;
    regenerate?: boolean;
    edit?: boolean;
  },
) {
  const candidatePool = provider.models.filter((item) =>
    options?.edit ? canEditRealImage(item) : canGenerateRealImage(item),
  );

  const defaultKey = options?.edit
    ? "isDefaultImageEdit"
    : options?.regenerate
      ? "isDefaultDetailImage"
      : "isDefaultHeroImage";

  if (options?.preferredModelId) {
    return [options.preferredModelId];
  }

  const configuredDefault =
    candidatePool.find((item) => Boolean(item[defaultKey]))?.modelId ??
    (!options?.edit ? candidatePool.find((item) => item.isDefaultDetailImage)?.modelId : null);

  if (configuredDefault) {
    return [configuredDefault];
  }

  const candidates = [
    ...candidatePool
      .filter((item) => isStableImageModel(item.modelId) && isPreferredImageModel(item.modelId))
      .map((item) => item.modelId),
    ...candidatePool.filter((item) => isStableImageModel(item.modelId)).map((item) => item.modelId),
    ...candidatePool.filter((item) => isPreferredImageModel(item.modelId)).map((item) => item.modelId),
    ...candidatePool.map((item) => item.modelId),
  ].filter(Boolean) as string[];

  return [...new Set(candidates)];
}

function buildSvgModelCandidates(provider: ProviderContext) {
  const visionText = provider.models.filter((item) => hasTextCapability(item) && hasVisionCapability(item));
  const textOnly = provider.models.filter((item) => hasTextCapability(item));

  const candidates = [
    provider.models.find((item) => item.isDefaultPlanning)?.modelId ?? null,
    provider.models.find((item) => item.isDefaultAnalysis)?.modelId ?? null,
    ...visionText
      .filter((item) => /gemini|gpt-4o|gpt-5/i.test(item.modelId) && !/preview|experimental|beta|test/i.test(item.modelId))
      .map((item) => item.modelId),
    ...visionText.filter((item) => !/preview|experimental|beta|test/i.test(item.modelId)).map((item) => item.modelId),
    ...textOnly
      .filter((item) => /gemini|gpt-4o|gpt-5/i.test(item.modelId) && !/preview|experimental|beta|test/i.test(item.modelId))
      .map((item) => item.modelId),
    ...textOnly.filter((item) => !/preview|experimental|beta|test/i.test(item.modelId)).map((item) => item.modelId),
    ...textOnly.map((item) => item.modelId),
  ].filter(Boolean) as string[];

  return [...new Set(candidates)];
}

function shouldFallbackToNextImageModel(error: unknown) {
  if (!(error instanceof Error)) {
    return false;
  }

  if (
    /monthly spending limit|spending limit|billing|quota|insufficient_quota|403|forbidden|unauthorized|invalid token|api key|429|rate limit|限流/i.test(
      error.message,
    )
  ) {
    return false;
  }

  return /404|405|no available endpoint|unsupported|not implemented|does not exist|invalid_value|unknown parameter|invalid type|supported values|invalid value.+size/i.test(
    error.message,
  );
}

function isTransientImageNetworkFailure(detail: string) {
  return /fetch failed|timed out|timeout|network error|socket hang up|ECONNRESET|ECONNREFUSED|ETIMEDOUT|ENOTFOUND/i.test(detail);
}

function buildTransientImageNetworkMessage(detail: string) {
  return "\u5f53\u524d\u56fe\u7247\u751f\u6210\u8bf7\u6c42\u7f51\u7edc\u5931\u8d25\u6216\u4ee3\u7406\u4e34\u65f6\u4e2d\u65ad\uff0c\u8bf7\u7a0d\u540e\u91cd\u8bd5\u3002\u5f53\u524d\u6a21\u578b\u7aef\u70b9\u5df2\u5728\u672c\u8f6e\u751f\u6210\u4e2d\u6210\u529f\u8fd4\u56de\u8fc7\u56fe\u7247\uff0c\u8fd9\u4e0d\u662f Provider \u4e0d\u652f\u6301\u56fe\u7247\u751f\u6210\u3002\u539f\u59cb\u9519\u8bef\uff1a" + detail;
}

function summarizeProviderImageFailure(detail: string, mode: "generate" | "edit") {
  const reasons: string[] = [];

  if (/model.+does not exist|invalid_value.+model/i.test(detail)) {
    reasons.push("代理商返回的图片模型名称无效或并不存在");
  }
  if (/no available endpoint|404/i.test(detail)) {
    reasons.push("代理商没有为这些模型开放真实图片端点");
  }
  if (/429|限流|rate limit/i.test(detail)) {
    reasons.push("代理商图片接口当前触发了限流");
  }
  if (/unknown parameter|invalid type|images\[0\]|supported values|invalid value.+size/i.test(detail)) {
    reasons.push("代理商图片接口的兼容格式与当前网关实现不一致");
  }

  if (!reasons.length) {
    reasons.push(mode === "edit" ? "图像编辑接口暂时不可用" : "图像生成接口暂时不可用");
  }

  return [...new Set(reasons)].join("；");
}

function extractJsonBlock(raw: string) {
  const direct = raw.trim();
  if (direct.startsWith("{") || direct.startsWith("[")) {
    return direct;
  }

  const fencedMatch = direct.match(/```json([\s\S]*?)```/i) || direct.match(/```([\s\S]*?)```/i);
  if (fencedMatch?.[1]) {
    return fencedMatch[1].trim();
  }

  const firstBrace = direct.indexOf("{");
  const lastBrace = direct.lastIndexOf("}");
  if (firstBrace >= 0 && lastBrace > firstBrace) {
    return direct.slice(firstBrace, lastBrace + 1);
  }

  return direct;
}

function escapeXml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

async function assetToDataUrl(asset: Pick<AssetRecord, "filePath" | "mimeType">) {
  const buffer = await readStorageFile(asset.filePath);
  const mimeType = asset.mimeType ?? "image/png";
  return `data:${mimeType};base64,${buffer.toString("base64")}`;
}

function pickPrimaryProductAsset(projectAssets: AssetRecord[]) {
  return (
    projectAssets.find((asset) => asset.isMain) ??
    projectAssets.find((asset) => asset.type === "MAIN") ??
    projectAssets.find((asset) => ["ANGLE", "DETAIL", "REFERENCE"].includes(asset.type)) ??
    projectAssets[0] ??
    null
  );
}

function mergeReferenceAssets(projectAssets: AssetRecord[], explicitReferenceAssets: AssetRecord[]) {
  const primaryAsset = pickPrimaryProductAsset(projectAssets);
  const merged = [primaryAsset, ...explicitReferenceAssets].filter(Boolean) as AssetRecord[];

  return merged.filter((asset, index, list) => list.findIndex((entry) => entry.id === asset.id) === index);
}

async function resolveReferenceAssets(referenceAssetIds: string[]) {
  if (!referenceAssetIds.length) {
    return [];
  }

  return prisma.productAsset.findMany({
    where: { id: { in: referenceAssetIds } },
  });
}

async function persistSectionVersion(params: {
  sectionId: string;
  imageAssetId: string;
  promptSnapshot: string;
  copySnapshot: string;
}) {
  const lastVersion = await prisma.sectionVersion.findFirst({
    where: { sectionId: params.sectionId },
    orderBy: { versionNumber: "desc" },
  });

  const versionNumber = (lastVersion?.versionNumber ?? 0) + 1;

  await prisma.sectionVersion.updateMany({
    where: { sectionId: params.sectionId },
    data: { isActive: false },
  });

  return prisma.sectionVersion.create({
    data: {
      sectionId: params.sectionId,
      versionNumber,
      promptSnapshot: { prompt: params.promptSnapshot },
      copySnapshot: { copy: params.copySnapshot },
      imageAssetId: params.imageAssetId,
      isActive: true,
    },
  });
}

async function generateWithFallback(params: {
  adapter: AdapterContext;
  candidateModels: string[];
  prompt: string;
  size: string;
  aspectRatio: SectionImageAspectRatio;
  referenceImages: string[];
  projectId: string;
  sectionId: string;
  operation: string;
}) {
  const errors: string[] = [];

  for (const model of params.candidateModels) {
    try {
      const generated = await params.adapter.generateImage({
        model,
        prompt: params.prompt,
        size: params.size,
        aspectRatio: params.aspectRatio,
        referenceImages: params.referenceImages,
        monitor: {
          projectId: params.projectId,
          sectionId: params.sectionId,
          operation: params.operation,
        },
      });

      return {
        model,
        generated,
        attemptedModels: params.candidateModels,
      };
    } catch (error) {
      const message = error instanceof Error ? error.message : "Unknown image generation error";
      errors.push(`${model}: ${message}`);

      if (!shouldFallbackToNextImageModel(error)) {
        throw error;
      }
    }
  }

  throw new Error(`所有可用图片模型都生成失败：${errors.join(" | ")}`);
}

async function editWithFallback(params: {
  adapter: AdapterContext;
  candidateModels: string[];
  prompt: string;
  image: string;
  size: string;
  aspectRatio: SectionImageAspectRatio;
  referenceImages: string[];
  projectId: string;
  sectionId: string;
  operation: string;
}) {
  const errors: string[] = [];

  for (const model of params.candidateModels) {
    try {
      const generated = await params.adapter.editImage({
        model,
        prompt: params.prompt,
        image: params.image,
        size: params.size,
        aspectRatio: params.aspectRatio,
        referenceImages: params.referenceImages,
        monitor: {
          projectId: params.projectId,
          sectionId: params.sectionId,
          operation: params.operation,
        },
      });

      return {
        model,
        generated,
        attemptedModels: params.candidateModels,
      };
    } catch (error) {
      const message = error instanceof Error ? error.message : "Unknown image edit error";
      errors.push(`${model}: ${message}`);

      if (!shouldFallbackToNextImageModel(error)) {
        throw error;
      }
    }
  }

  throw new Error(`所有可用图片编辑模型都处理失败：${errors.join(" | ")}`);
}

async function generateSvgLayoutSpec(params: {
  adapter: AdapterContext;
  candidateModels: string[];
  userPrompt: string;
  images: string[];
  projectId: string;
  sectionId: string;
  operation: string;
}) {
  const errors: string[] = [];

  for (const model of params.candidateModels) {
    try {
      const result = await params.adapter.generateText({
        model,
        systemPrompt: "Return one strict JSON object only. No markdown.",
        userPrompt: params.userPrompt,
        images: params.images,
        monitor: {
          projectId: params.projectId,
          sectionId: params.sectionId,
          operation: params.operation,
        },
      });

      const parsed = svgLayoutSchema.parse(JSON.parse(extractJsonBlock(result.text)));
      return {
        model,
        parsed,
      };
    } catch (error) {
      errors.push(`${model}: ${error instanceof Error ? error.message : "Unknown SVG layout error"}`);
    }
  }

  throw new Error(`SVG 版式生成失败：${errors.join(" | ")}`);
}

function composeSectionSvg(params: {
  section: { title: string; copy: string; type: string };
  layout: z.infer<typeof svgLayoutSchema>;
  productImageDataUrl?: string | null;
  contentLanguage: ContentLanguage;
}) {
  const uiCopy = svgCopyByLanguage[params.contentLanguage] ?? svgCopyByLanguage["en-US"]!;
  const sectionLabel =
    sectionTypeLabels[params.section.type.toLowerCase() as keyof typeof sectionTypeLabels] ?? params.section.type;
  const highlights = params.layout.highlights
    .map(
      (item, index) => `
      <g transform="translate(${90 + (index % 2) * 390}, ${1160 + Math.floor(index / 2) * 100})">
        <rect rx="26" ry="26" width="330" height="72" fill="${params.layout.panelColor}" opacity="0.95" />
        <text x="28" y="45" font-size="30" fill="${params.layout.accentColor}" font-weight="700">${escapeXml(item)}</text>
      </g>`,
    )
    .join("");

  const productImage = params.productImageDataUrl
    ? `<image href="${params.productImageDataUrl}" x="110" y="350" width="860" height="700" preserveAspectRatio="xMidYMid meet" clip-path="url(#productClip)" />`
    : `<rect x="110" y="350" width="860" height="700" rx="56" fill="${params.layout.panelColor}" />
       <text x="540" y="720" text-anchor="middle" font-size="42" fill="${params.layout.accentColor}" font-weight="700">${escapeXml(uiCopy.waitingForAsset)}</text>`;

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg width="1080" height="1920" viewBox="0 0 1080 1920" fill="none" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1080" y2="1920" gradientUnits="userSpaceOnUse">
      <stop stop-color="${params.layout.backgroundColor}" />
      <stop offset="1" stop-color="#FFFFFF" />
    </linearGradient>
    <clipPath id="productClip">
      <rect x="110" y="350" width="860" height="700" rx="56" ry="56" />
    </clipPath>
  </defs>

  <rect width="1080" height="1920" fill="url(#bg)" />
  <circle cx="930" cy="250" r="150" fill="${params.layout.accentColor}" opacity="0.12" />
  <circle cx="170" cy="1460" r="220" fill="${params.layout.accentColor}" opacity="0.08" />

  <rect x="72" y="84" rx="28" ry="28" width="260" height="66" fill="${params.layout.accentColor}" />
  <text x="202" y="127" text-anchor="middle" font-size="28" fill="#FFFFFF" font-weight="700">${escapeXml(params.layout.badge)}</text>

  <text x="80" y="220" font-size="66" fill="#1F1720" font-weight="800">${escapeXml(params.layout.headline)}</text>
  <text x="80" y="292" font-size="34" fill="#5C515A" font-weight="500">${escapeXml(params.layout.subheadline)}</text>

  <g>
    <rect x="110" y="350" width="860" height="700" rx="56" fill="#FFFFFF" opacity="0.78" />
    ${productImage}
  </g>

  <rect x="72" y="1090" width="936" height="340" rx="44" fill="#FFFFFF" opacity="0.82" />
  <text x="112" y="1160" font-size="34" fill="#3A3139" font-weight="700">${escapeXml(uiCopy.highlights)}</text>
  ${highlights}

  <rect x="72" y="1468" width="936" height="280" rx="44" fill="${params.layout.panelColor}" opacity="0.98" />
  <text x="112" y="1540" font-size="34" fill="${params.layout.accentColor}" font-weight="800">${escapeXml(sectionLabel)}</text>
  <text x="112" y="1602" font-size="48" fill="#1F1720" font-weight="800">${escapeXml(params.section.title)}</text>
  <text x="112" y="1670" font-size="30" fill="#5A4E58" font-weight="500">${escapeXml(params.section.copy || params.layout.subheadline)}</text>

  <rect x="72" y="1788" width="936" height="88" rx="44" fill="${params.layout.accentColor}" />
  <text x="540" y="1844" text-anchor="middle" font-size="34" fill="#FFFFFF" font-weight="800">${escapeXml(uiCopy.footer)}</text>
</svg>`;
}

async function generateSvgFallback(params: {
  section: PageSection;
  adapter: AdapterContext;
  provider: ProviderContext;
  referenceAssets: AssetRecord[];
  aspectRatio: SectionImageAspectRatio;
  contentLanguage: ContentLanguage;
}) {
  const modelCandidates = buildSvgModelCandidates(params.provider);
  if (!modelCandidates.length) {
    throw new Error("当前 Provider 没有可用于 SVG 兜底预览的文本模型。");
  }

  const selectedAssets = params.referenceAssets.slice(0, 4);
  const imageInputs = await Promise.all(selectedAssets.map((asset) => assetToDataUrl(asset)));
  const layoutSpec = await generateSvgLayoutSpec({
    adapter: params.adapter,
    candidateModels: modelCandidates,
    userPrompt: buildSectionSvgLayoutPrompt(
      params.section,
      params.referenceAssets as ProductAsset[],
      params.aspectRatio,
      params.contentLanguage,
    ),
    images: imageInputs,
    projectId: params.section.projectId,
    sectionId: params.section.id,
    operation: "svg_fallback_layout",
  });

  const productImageAsset = params.referenceAssets[0] ?? null;
  const productImageDataUrl = productImageAsset ? await assetToDataUrl(productImageAsset) : null;
  const svgText = composeSectionSvg({
    section: {
      title: params.section.title,
      copy: params.section.copy,
      type: params.section.type,
    },
    layout: layoutSpec.parsed,
    productImageDataUrl,
    contentLanguage: params.contentLanguage,
  });

  return {
    svgText,
    model: layoutSpec.model,
    layout: layoutSpec.parsed,
  };
}

async function generateSectionImageInternal(
  projectId: string,
  sectionId: string,
  options?: {
    preferredModelId?: string | null;
    referenceAssetIds?: string[];
    regenerate?: boolean;
  },
) {
  const project = await prisma.project.findUnique({
    where: { id: projectId },
    include: {
      assets: { orderBy: [{ isMain: "desc" }, { sortOrder: "asc" }, { createdAt: "asc" }] },
      analysis: true,
    },
  });

  const section = await prisma.pageSection.findUnique({
    where: { id: sectionId },
  });

  if (!project) {
    throw new Error("Project not found.");
  }

  if (!section || section.projectId !== projectId) {
    throw new Error("Section not found.");
  }

  const { provider, adapter } = await getProviderAdapter();
  const generationSettings = getGenerationSettings(project);
  const visualStyleGuide = getProjectVisualStyleGuide(project);
  const generationRequirements = readGenerationRequirements(project.analysis?.normalizedResult);
  const sectionAspectRatio = getSectionAspectRatio(section, generationSettings.imageAspectRatio);
  const outputSize = getOutputSize(sectionAspectRatio);
  const modelCandidates = buildImageModelCandidates(provider, options);
  const selectedModel = modelCandidates[0] ?? null;
  const explicitReferenceAssets = await resolveReferenceAssets(options?.referenceAssetIds ?? []);
  const effectiveReferenceAssets = mergeReferenceAssets(project.assets as AssetRecord[], explicitReferenceAssets as AssetRecord[]);
  const referenceImages = await Promise.all(effectiveReferenceAssets.map((asset) => assetToDataUrl(asset)));
  const runningTask = await findRecentRunningTask({
    projectId,
    sectionId,
    taskType: options?.regenerate ? "REGENERATE" : "GENERATE",
    maxAgeMinutes: 20,
  });
  if (runningTask) {
    throw new Error("当前模块图仍在生成中，请等待这一轮完成后再试。");
  }

  const task = await createTask({
    projectId,
    sectionId,
    taskType: options?.regenerate ? "REGENERATE" : "GENERATE",
    inputPayload: {
      model: selectedModel,
      modelCandidates,
      referenceAssetIds: options?.referenceAssetIds ?? [],
      effectiveReferenceAssetIds: effectiveReferenceAssets.map((asset) => asset.id),
      allowSvgFallback: generationSettings.allowSvgFallback,
    },
  });

  await prisma.pageSection.update({
    where: { id: sectionId },
    data: { status: "GENERATING" },
  });

  try {
    const basePrompt = options?.regenerate
      ? buildRegenerationPrompt(
          section,
          effectiveReferenceAssets as ProductAsset[],
          sectionAspectRatio,
          generationSettings.contentLanguage,
          generationRequirements,
        )
      : buildSectionImagePrompt(
          section,
          effectiveReferenceAssets as ProductAsset[],
          sectionAspectRatio,
          generationSettings.contentLanguage,
          generationRequirements,
        );
    const prompt = await buildVisualPromptWithAgent({
      provider,
      adapter,
      mode: "ecommerce_section",
      title: section.title,
      goal: section.goal,
      copy: section.copy,
      basePrompt,
      aspectRatio: sectionAspectRatio,
      contentLanguage: generationSettings.contentLanguage,
      referenceImages,
      referenceAssets: effectiveReferenceAssets as ProductAsset[],
      productContext: project.analysis?.normalizedResult ?? project.modelSnapshot ?? null,
      visualStyleGuide,
      projectId,
      sectionId,
      operation: options?.regenerate ? "visual_prompt_agent_regenerate_section" : "visual_prompt_agent_generate_section",
    });

    let imageAsset;
    let version;
    let usedModel: string;
    let generationMode: "image_api" | "svg_fallback";

    try {
      if (!selectedModel) {
        throw new Error("当前 Provider 没有识别到可用于真实图片生成的模型。");
      }

      const generation = await generateWithFallback({
        adapter,
        candidateModels: modelCandidates,
        prompt,
        size: outputSize,
        aspectRatio: sectionAspectRatio,
        referenceImages,
        projectId,
        sectionId,
        operation: options?.regenerate ? "regenerate_section_image" : "generate_section_image",
      });

      imageAsset = await saveGeneratedImage({
        projectId,
        sectionId,
        prompt,
        source: generation.generated,
        metadata: {
          mode: "image_api",
          usedModel: generation.model,
          sourceReferenceAssetIds: effectiveReferenceAssets.map((asset) => asset.id),
          primaryReferenceAssetId: effectiveReferenceAssets[0]?.id ?? null,
        },
      });

      usedModel = generation.model;
      generationMode = "image_api";
    } catch (error) {
      if (!generationSettings.allowSvgFallback) {
        const detail = error instanceof Error ? error.message : "Unknown image generation error";
        if (/monthly spending limit|spending limit|billing|quota/i.test(detail)) {
          throw new Error("当前 API Key 的图片生成额度已用尽。请前往代理商控制台提高或移除月度限额，或更换可用的 API Key。");
        }
        if (isTransientImageNetworkFailure(detail)) {
          throw new Error(buildTransientImageNetworkMessage(detail));
        }
        const summary = summarizeProviderImageFailure(detail, "generate");
        throw new Error(
          `当前 Provider 没有可用的真实图片生成端点。请前往“模型服务配置”页更换支持图片生成的 Provider，或在规划页手动开启“允许 SVG 兜底预览”。原因摘要：${summary}`,
        );
      }

      const fallback = await generateSvgFallback({
        section,
        adapter,
        provider,
        referenceAssets: effectiveReferenceAssets,
        aspectRatio: sectionAspectRatio,
        contentLanguage: generationSettings.contentLanguage,
      });

      imageAsset = await saveGeneratedImage({
        projectId,
        sectionId,
        prompt,
        source: {
          svgText: fallback.svgText,
          mimeType: "image/svg+xml",
        },
        metadata: {
          mode: "svg_fallback",
          usedModel: fallback.model,
          layout: fallback.layout,
          sourceReferenceAssetIds: effectiveReferenceAssets.map((asset) => asset.id),
          primaryReferenceAssetId: effectiveReferenceAssets[0]?.id ?? null,
          imageApiError: error instanceof Error ? error.message : "Unknown image api error",
        },
      });

      usedModel = fallback.model;
      generationMode = "svg_fallback";
    }

    version = await persistSectionVersion({
      sectionId,
      imageAssetId: imageAsset.id,
      promptSnapshot: prompt,
      copySnapshot: section.copy,
    });

    await prisma.pageSection.update({
      where: { id: sectionId },
      data: {
        status: "SUCCESS",
        currentImageAssetId: imageAsset.id,
      },
    });

    await prisma.project.update({
      where: { id: projectId },
      data: {
        status: "EDITING",
      },
    });

    await completeTask(task.id, {
      imageAssetId: imageAsset.id,
      versionId: version.id,
      usedModel,
      generationMode,
      sourceReferenceAssetIds: effectiveReferenceAssets.map((asset) => asset.id),
    });

    return { imageAsset, version, usedModel, generationMode };
  } catch (error) {
    await prisma.pageSection.update({
      where: { id: sectionId },
      data: {
        status: "FAILED",
      },
    });

    await failTask(task.id, error instanceof Error ? error.message : "Image generation failed");
    throw error;
  }
}

export async function generateSectionImage(
  projectId: string,
  sectionId: string,
  preferredModelId?: string | null,
  referenceAssetIds?: string[],
) {
  return generateSectionImageInternal(projectId, sectionId, {
    preferredModelId,
    referenceAssetIds,
    regenerate: false,
  });
}

export async function regenerateSectionImage(
  projectId: string,
  sectionId: string,
  preferredModelId?: string | null,
  referenceAssetIds?: string[],
) {
  return generateSectionImageInternal(projectId, sectionId, {
    preferredModelId,
    referenceAssetIds,
    regenerate: true,
  });
}

export async function editSectionImage(
  projectId: string,
  sectionId: string,
  options?: {
    preferredModelId?: string | null;
    referenceAssetIds?: string[];
    editMode?: "repaint" | "enhance" | "translate";
    targetLanguage?: ContentLanguage;
  },
) {
  const project = await prisma.project.findUnique({
    where: { id: projectId },
    include: {
      assets: { orderBy: [{ isMain: "desc" }, { sortOrder: "asc" }, { createdAt: "asc" }] },
      analysis: true,
    },
  });

  const section = await prisma.pageSection.findUnique({
    where: { id: sectionId },
    include: {
      currentImageAsset: true,
    },
  });

  if (!project) {
    throw new Error("Project not found.");
  }

  if (!section || section.projectId !== projectId) {
    throw new Error("Section not found.");
  }

  if (!section.currentImageAsset) {
    throw new Error("当前模块还没有可编辑的底图，请先生成一张模块图。");
  }

  const { provider, adapter } = await getProviderAdapter();
  const generationSettings = getGenerationSettings(project);
  const visualStyleGuide = getProjectVisualStyleGuide(project);
  const generationRequirements = readGenerationRequirements(project.analysis?.normalizedResult);
  const sectionAspectRatio = getSectionAspectRatio(section, generationSettings.imageAspectRatio);
  const outputSize = getOutputSize(sectionAspectRatio);
  const modelCandidates = buildImageModelCandidates(provider, {
    preferredModelId: options?.preferredModelId,
    edit: true,
    regenerate: true,
  });
  const selectedModel = modelCandidates[0] ?? null;
  const explicitReferenceAssets = await resolveReferenceAssets(options?.referenceAssetIds ?? []);
  const productReferenceAssets = mergeReferenceAssets(project.assets as AssetRecord[], explicitReferenceAssets as AssetRecord[]);
  const baseImage = await assetToDataUrl(section.currentImageAsset as AssetRecord);
  const referenceImages = await Promise.all(
    productReferenceAssets
      .filter((asset) => asset.id !== section.currentImageAssetId)
      .map((asset) => assetToDataUrl(asset)),
  );
  const editMode = options?.editMode ?? "repaint";
  const effectiveContentLanguage = editMode === "translate" ? normalizeContentLanguage(options?.targetLanguage) : generationSettings.contentLanguage;
  const runningTask = await findRecentRunningTask({
    projectId,
    sectionId,
    taskType: "REGENERATE",
    maxAgeMinutes: 20,
  });
  if (runningTask) {
    throw new Error("当前模块图仍在重绘或增强中，请等待这一轮完成后再试。");
  }

  const task = await createTask({
    projectId,
    sectionId,
    taskType: "REGENERATE",
    inputPayload: {
      mode: "edit_image",
      editMode,
      targetLanguage: editMode === "translate" ? effectiveContentLanguage : undefined,
      model: selectedModel,
      modelCandidates,
      baseImageAssetId: section.currentImageAssetId,
      referenceAssetIds: options?.referenceAssetIds ?? [],
      effectiveReferenceAssetIds: productReferenceAssets.map((asset) => asset.id),
      allowSvgFallback: generationSettings.allowSvgFallback,
    },
  });

  await prisma.pageSection.update({
    where: { id: sectionId },
    data: { status: "GENERATING" },
  });

  try {
    const basePrompt = buildImageEditPrompt(
      section,
      productReferenceAssets as ProductAsset[],
      editMode,
      sectionAspectRatio,
      effectiveContentLanguage,
      generationRequirements,
    );
    const prompt = await buildVisualPromptWithAgent({
      provider,
      adapter,
      mode: "image_edit",
      title: section.title,
      goal: section.goal,
      copy: section.copy,
      basePrompt,
      aspectRatio: sectionAspectRatio,
      contentLanguage: effectiveContentLanguage,
      referenceImages: [baseImage, ...referenceImages],
      referenceAssets: productReferenceAssets as ProductAsset[],
      productContext: project.analysis?.normalizedResult ?? project.modelSnapshot ?? null,
      visualStyleGuide,
      projectId,
      sectionId,
      operation: editMode === "translate" ? "visual_prompt_agent_translate_section" : editMode === "enhance" ? "visual_prompt_agent_enhance_section" : "visual_prompt_agent_repaint_section",
    });

    let imageAsset;
    let version;
    let usedModel: string;
    let generationMode: "image_api" | "svg_fallback";

    try {
      if (!selectedModel) {
        throw new Error("当前 Provider 没有识别到可用于真实图片编辑的模型。");
      }

      const generation = await editWithFallback({
        adapter,
        candidateModels: modelCandidates,
        prompt,
        image: baseImage,
        size: outputSize,
        aspectRatio: sectionAspectRatio,
        referenceImages,
        projectId,
        sectionId,
        operation: editMode === "translate" ? "translate_section_image" : editMode === "enhance" ? "enhance_section_image" : "repaint_section_image",
      });

      imageAsset = await saveGeneratedImage({
        projectId,
        sectionId,
        prompt,
        source: generation.generated,
        metadata: {
          mode: "image_api",
          usedModel: generation.model,
          editMode,
          targetLanguage: editMode === "translate" ? effectiveContentLanguage : undefined,
          baseImageAssetId: section.currentImageAssetId,
          sourceReferenceAssetIds: productReferenceAssets.map((asset) => asset.id),
          primaryReferenceAssetId: productReferenceAssets[0]?.id ?? null,
        },
      });

      usedModel = generation.model;
      generationMode = "image_api";
    } catch (error) {
      if (!generationSettings.allowSvgFallback) {
        const detail = error instanceof Error ? error.message : "Unknown image edit error";
        if (/monthly spending limit|spending limit|billing|quota/i.test(detail)) {
          throw new Error("当前 API Key 的图片编辑/生成额度已用尽。请前往代理商控制台提高或移除月度限额，或更换可用的 API Key。");
        }
        if (isTransientImageNetworkFailure(detail)) {
          throw new Error(buildTransientImageNetworkMessage(detail));
        }
        const summary = summarizeProviderImageFailure(detail, "edit");
        throw new Error(
          `当前 Provider 没有可用的真实图片生成或编辑端点。请前往“模型服务配置”页更换支持图片编辑的 Provider，或在规划页手动开启“允许 SVG 兜底预览”。原因摘要：${summary}`,
        );
      }

      const fallback = await generateSvgFallback({
        section,
        adapter,
        provider,
        referenceAssets: productReferenceAssets,
        aspectRatio: sectionAspectRatio,
        contentLanguage: generationSettings.contentLanguage,
      });

      imageAsset = await saveGeneratedImage({
        projectId,
        sectionId,
        prompt,
        source: {
          svgText: fallback.svgText,
          mimeType: "image/svg+xml",
        },
        metadata: {
          mode: "svg_fallback",
          usedModel: fallback.model,
          editMode,
          targetLanguage: editMode === "translate" ? effectiveContentLanguage : undefined,
          baseImageAssetId: section.currentImageAssetId,
          layout: fallback.layout,
          sourceReferenceAssetIds: productReferenceAssets.map((asset) => asset.id),
          primaryReferenceAssetId: productReferenceAssets[0]?.id ?? null,
          imageApiError: error instanceof Error ? error.message : "Unknown image edit api error",
        },
      });

      usedModel = fallback.model;
      generationMode = "svg_fallback";
    }

    version = await persistSectionVersion({
      sectionId,
      imageAssetId: imageAsset.id,
      promptSnapshot: prompt,
      copySnapshot: section.copy,
    });

    await prisma.pageSection.update({
      where: { id: sectionId },
      data: {
        status: "SUCCESS",
        currentImageAssetId: imageAsset.id,
      },
    });

    await prisma.project.update({
      where: { id: projectId },
      data: {
        status: "EDITING",
      },
    });

    await completeTask(task.id, {
      mode: "edit_image",
      editMode,
      targetLanguage: editMode === "translate" ? effectiveContentLanguage : undefined,
      imageAssetId: imageAsset.id,
      versionId: version.id,
      usedModel,
      generationMode,
      baseImageAssetId: section.currentImageAssetId,
      sourceReferenceAssetIds: productReferenceAssets.map((asset) => asset.id),
    });

    return { imageAsset, version, usedModel, generationMode, editMode, targetLanguage: editMode === "translate" ? effectiveContentLanguage : undefined };
  } catch (error) {
    await prisma.pageSection.update({
      where: { id: sectionId },
      data: {
        status: "FAILED",
      },
    });

    await failTask(task.id, error instanceof Error ? error.message : "Image edit failed");
    throw error;
  }
}

export async function listSectionVersions(sectionId: string) {
  return prisma.sectionVersion.findMany({
    where: { sectionId },
    orderBy: { versionNumber: "desc" },
    include: {
      imageAsset: true,
    },
  });
}

export async function activateSectionVersion(sectionId: string, versionId: string) {
  const version = await prisma.sectionVersion.findUnique({
    where: { id: versionId },
  });

  if (!version || version.sectionId !== sectionId) {
    throw new Error("Version not found.");
  }

  await prisma.sectionVersion.updateMany({
    where: { sectionId },
    data: { isActive: false },
  });

  await prisma.sectionVersion.update({
    where: { id: versionId },
    data: { isActive: true },
  });

  await prisma.pageSection.update({
    where: { id: sectionId },
    data: {
      currentImageAssetId: version.imageAssetId,
      status: "SUCCESS",
    },
  });

  return prisma.sectionVersion.findUnique({
    where: { id: versionId },
    include: { imageAsset: true },
  });
}
